commands:
  groups:
    commands:
      opdocker:
        type: wrapper
        args:
          wrapper: base_wrapper
          command: opdocker
        description: "Manage docker environment (optaros) in current directory"
        commands:
          up:
            type: cli
            description: Start docker stack
            args:
              command: ./m2-cluster -d up
          halt:
            type: cli
            description: Stop docker stack
            args:
              command: ./m2-cluster halt
          magento:
            type: cli
            description: shell magento tools
            args:
              wrapper: base_wrapper
              command: ./m2-cluster magento
              params:
                subcommand:
                  type: list
                  name: ""
                  message: "Choose a sub-command: "
                  choices:
                    - name: cache:flush
                      value: cache:flush
                    - name: setup:upgrade
                      value: setup:upgrade
                message:
                  message: 'Enter a commit message: '
                  type: input
                  name: -m
                  validate: PhoneNumberValidator
                  output_format: "\"$value\""

          cli_info:
            type: cli
            description: Show cli info
            args:
              command: 'git name-rev --name-only HEAD && echo "Docker: running"'
              config:
                output: list
                verbose: False

commands_defaults:
  opdocker:
    start_message: Starting docker stack