#!/usr/bin/env python3
import os
import sys

from src.lcli.__main__ import main


CURRENT_DIRECTORY = os.path.dirname(os.path.abspath(__file__))
BASE_PATH = os.path.join(CURRENT_DIRECTORY, "src")
sys.path.insert(0, BASE_PATH)


if __name__ == "__main__":
    main(
        {
            "flags": [
                "-d",
                "-v",
            ]
        }
    )
