all:
  hosts:
    db_server1:
      ansible_connection: local
    db_server2:
      ansible_connection: local
    db_server3:
      ansible_connection: local
    web_server1:
      ansible_connection: local
    web_server2:
      ansible_connection: local
    web_server3:
      ansible_connection: local
  children:
    web_servers:
      hosts:
        web_server1:
        web_server2:
        web_server3:
    db_servers:
      hosts:
        db_server1:
        db_server2:
        db_server3:
